fix - fix typo strip_escapes
freebsd/freebsd-src pull request #1025
Opened 2024-01-11 22:28 UTC by chiajungchang2003

- "return copy..."  to "return a copy..."

2024-01-11 22:33 UTC, chiajungchang2003 commented
Name: Chia-Jung Chang
Email: maluma110020036@nthu.edu.tw
Line1292: return copy -> return a copy
Event: This is from the Advanced UNIX programming course (Fall'23) at NTHU

2024-01-12 04:07 UTC, rilysh requested changes
See https://github.com/freebsd/freebsd-src/pull/951#issuecomment-1869693910
e.g.
```
<place your commit message>

Event: Advanced UNIX Programming Course (Fall’23) at NTHU.
```
Same applies to #1026 and #1028  (with different commit message for each one).

2024-01-12 05:41 UTC, chiajungchang2003 commented
> See [#951 (comment)](https://github.com/freebsd/freebsd-src/pull/951#issuecomment-1869693910) e.g.
> 
> ```
> <place your commit message>
> 
> Event: Advanced UNIX Programming Course (Fall’23) at NTHU.
> ```
> 
> Same applies to #1026 and #1028 (with different commit message for each one).

Thanks, I've changed the format

2024-01-15 16:05 UTC, lwhsu commented
See https://patch-diff.githubusercontent.com/raw/freebsd/freebsd-src/pull/1025.patch

Please include `Event: Advanced UNIX programming course (Fall'23) at NTHU` in the last line of your comment message. You can use `git commit --amend` and `git push -f` to update your branch and the pull request.

2024-02-13 11:08 UTC, lwhsu commented
Merged as a400e2590416949987dab710930ffd94539a545a

2024-02-13 11:08 UTC, closed without merging