find: Allow '/' to be used with -perm for GNU compatibility
freebsd/freebsd-src pull request #1060
Opened 2024-01-14 15:20 UTC by ricardobranco777

Since 2005 GNU find(1) no longer allows '+' to be used with `-perm`, forcing the use of a `/` instead.

This PR adds support for this character as synonym for '+'.

2024-01-14 16:57 UTC, igalic commented
I feel like this would require a documentation update

2024-01-14 17:22 UTC, ricardobranco777 commented
> I feel like this would require a documentation update

Fixed.

2024-01-14 17:24 UTC, bsdimp commented
Can you rebase to a newer main and do a `git push --force-with-lease` so that the style checker also runs.

To my eyeballs, though, this looks good.

2024-01-14 17:26 UTC, ricardobranco777 commented
> --force-with-lease

Done.

2024-01-14 22:27 UTC, igalic requested changes
one final request
looks fine otherwise

2024-01-14 22:27 UTC, igalic commented on usr.bin/find/find.1
this gilt will need a  .Dd bump

2024-01-14 22:37 UTC, igalic requested changes
one final request

2024-01-15 01:39 UTC, qemu-bsd-user commented
Once the .Dd bump happens, I'll commit. It all looks good otherwise.
I also need to look at why my style checker didn't run with the forced push, but that's not the fault of the submitter...

2024-01-15 07:51 UTC, ricardobranco777 commented on usr.bin/find/find.1
Fixed. Thanks!

2024-01-15 07:51 UTC, ricardobranco777 commented
> Once the .Dd bump happens, I'll commit. It all looks good otherwise. I also need to look at why my style checker didn't run with the forced push, but that's not the fault of the submitter...

Fixed.

2024-01-15 15:05 UTC, jlduran commented
> I also need to look at why my style checker didn't run with the forced push

@bsdimp disguised as @qemu-bsd-user, maybe it is missing the `synchronize` activity type?
Ref: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request, yes it is the only activity type not in the past tense.

2024-01-15 15:55 UTC, emaste commented
I find `preceded by a plus (“+”) or a slash (“/”) (for GNU compatibility),` slightly awkward (although this entire `-perm` paragraph is already awkward).

I think `/` is not accepted by find on other BSDs or macOS, so we likely still prefer `+`? If the intent is to allow `/` for GNU compatibility but we feel that `+` is preferred I would probably leave the existing text intact, but add a sentence at the end along the lines of `For compatibility with GNU find a slash ("/") is also accepted in place of a plus ("+")`.

In any case the code change LGTM (and thanks for improving GNU compatibility).

2024-01-15 18:50 UTC, bsdimp commented
Merged. I hope it's OK, but I added a blurb in the STANDARDS section about this extension.

2024-01-15 18:50 UTC, closed without merging