find: Add -readable, -writable & -executable options
freebsd/freebsd-src pull request #1080
Opened 2024-01-21 20:12 UTC by ricardobranco777

Add -readable, -writable & -executable options for GNU find compatibility.  These functions use access() to test for readable/writable/executable access by the current user.

References:
- [GNU find manual](https://manpages.ubuntu.com/manpages/jammy/en/man1/find.1.html)

2024-01-21 20:29 UTC, igalic requested changes
a few nits i noticed on a first read thru

2024-01-21 20:29 UTC, igalic commented on usr.bin/find/find.1
> +Matches files which are executable by the current user. This test makes use of the
start new sentences on new lines

2024-01-21 20:29 UTC, igalic commented on usr.bin/find/find.1
> +.It Ic -readable
start new sentences on new lines

2024-01-21 20:29 UTC, igalic commented on usr.bin/find/find.1
> +Matches files which are writable by the current user. This test makes use of the
start new sentences on new lines

2024-01-21 20:29 UTC, igalic commented on usr.bin/find/option.c
> +	{ "-executable",c_simple,	f_executable,	0 },
space after comma

2024-01-21 20:38 UTC, ricardobranco777 commented on usr.bin/find/find.1
> +Matches files which are executable by the current user. This test makes use of the
Fixed.

2024-01-22 01:18 UTC, bsdjhb approved these changes

2024-01-22 01:18 UTC, bsdjhb commented on usr.bin/find/find.1
> +.\"	@(#)find.1	8.7 (Berkeley) 5/9/95
Mis-merge with changes in main to remove old SCCS IDs?

2024-01-22 01:19 UTC, bsdjhb commented
@bsdimp The style violations from the checker are false positives.

2024-01-22 01:25 UTC, igalic approved these changes
👍 (with @bsdjhb's complaint addressed)

2024-01-22 01:36 UTC, bsdjhb commented
Merged in e4b646ce16105efc943bc8ac2242a2220dfe18d8, thanks!

2024-01-22 01:36 UTC, closed without merging