Fork(2), exit(3), wait4(2): add simple test.
freebsd/freebsd-src pull request #1092
Opened 2024-02-01 11:37 UTC by LeeLin2602

Fork(2), exit(3), wait4(2): add simple test.

2024-02-01 11:45 UTC, lwhsu requested changes
I think the mtree needs updating as well.

2024-02-01 11:45 UTC, lwhsu commented on tests/sys/syscalls/Makefile
> +
superfluous white lines

2024-02-01 11:45 UTC, lwhsu commented on tests/sys/syscalls/fork/Makefile
> +
superfluous white lines

2024-02-01 11:45 UTC, lwhsu commented on tests/sys/syscalls/fork/fork_test.c
> + * Copyright (c) 2023 Lin Lee <leelin2602@gmail.com>
It's 2024 now.

2024-02-01 11:45 UTC, lwhsu commented on tests/sys/syscalls/fork/fork_test.c
> +
superfluous white lines

2024-02-01 11:45 UTC, lwhsu commented on tests/sys/syscalls/fork/fork_test.c
> + * ("CTSRD"), as part of the DARPA CRASH research programme.
Did you copy the file from the work of those projects? If so, you should add the copyright lines of them. If no, this part should be removed.

2024-02-01 11:48 UTC, igalic commented on tests/sys/syscalls/fork/fork_test.c
> + * ("CTSRD"), as part of the DARPA CRASH research programme.
is this just a copy paste again?

2024-02-03 05:12 UTC, LeeLin2602 commented
Please look into https://github.com/freebsd/freebsd-src/pull/1097.

2024-02-03 05:12 UTC, closed without merging