at cron file now lives in /etc/cron.d/at
freebsd/freebsd-src pull request #1106
Opened 2024-02-06 20:42 UTC by kravietz

Fix https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=243380

2024-02-06 23:35 UTC, igalic requested changes
This doesn't need to be 3 commits.

also see inline comments.

(I still wish github, or literally any forge out there, would render nroff / mdoc files)

2024-02-06 23:35 UTC, igalic commented on usr.sbin/cron/crontab/crontab.5
> +
empty lines is not how you generate a paragraph in mandoc, you use `.Pp`

2024-02-06 23:35 UTC, igalic commented on usr.sbin/cron/crontab/crontab.5
> +
use `.Pp` if you want to generate a new paragraph.

2024-02-06 23:35 UTC, igalic commented on usr.sbin/cron/crontab/crontab.5
If you think this is a significant change, then this file needs a `.Dd` bump

2024-02-07 16:42 UTC, kravietz commented
@igalic Thanks for all suggestion, fixed! Commits can be squashed into one on merge, if I remember correctly.

2024-04-23 13:38 UTC, emaste commented
> Commits can be squashed into one on merge, if I remember correctly.

We don't (can't) use the GitHub merge functionality, as GitHub is not the primary repository and does not have direct write access. It is possible for the FreeBSD committer who lands this to edit or squash the commits but we prefer that pull requests have commits prepared in a ready-to-land state.

Also please note from CONTRIBUTING.md:
* Commits should include one or more `Signed-off-by:` lines with full name and email address certifying [Developer Certificate of Origin](https://developercertificate.org/).

2024-04-23 14:06 UTC, bsdimp commented on usr.sbin/cron/crontab/crontab.5
> +
This is an extra newline and should be removed.

2024-05-10 04:37 UTC, bsdimp commented
Pushed with minor tweaks.

2024-05-10 04:38 UTC, bsdimp commented
Sorry this took so long to land... Thanks for fixing this and cross referencing the bug.

2024-05-10 04:40 UTC, merged