Resolution of a few self-reference entries in bhnd_erom.9 device_add_child.9 cfumass.4
freebsd/freebsd-src pull request #1129
Opened 2024-03-01 03:32 UTC by chrisdavidson

bhnd_erom.9 - fixed self reference entry .Xr -> .Nm
device_add_child.9 - fixed self reference entry .Xr -> .Nm
cfumass.4 - fixed self reference entry .Xr -> .Nm

2024-03-01 03:56 UTC, bsdimp commented on lib/libsys/open.2
> +.Nm openat 2
.Fn openat

2024-03-01 03:58 UTC, bsdimp commented on share/man/man4/cfumass.4
> +.Nm cfumass 4
.Nm cfumass

might be better. Or maybe even just .Nm

2024-03-01 03:59 UTC, bsdimp commented on share/man/man9/device_add_child.9
> +.Nm device_add_child 9 .
.Fn device_add_child .

2024-03-01 03:59 UTC, bsdimp commented on share/man/man9/device_add_child.9
> +.Nm device_add_child 9
.Fn device_add_child

(sorry if I mislead you)

2024-03-01 04:00 UTC, bsdimp commented
I think my advice on discord might have been wide of the mark.

2024-03-01 16:51 UTC, chrisdavidson commented on lib/libsys/open.2
> +.Nm openat 2
resolved in the latest commit

2024-03-01 16:51 UTC, chrisdavidson commented on share/man/man9/device_add_child.9
> +.Nm device_add_child 9 .
resolved in latest commit

2024-03-02 04:11 UTC, chrisdavidson commented
this pull request is now in a much better state than it was before. a rebase was performed to consolidate changes into one commit instead of 8 commits.

2024-03-07 08:23 UTC, concussious requested changes
There's an extra space at the end of line 326

2024-03-07 12:18 UTC, closed without merging