Update printf(3) based on latest OpenBSD structure and format
freebsd/freebsd-src pull request #1149
Opened 2024-03-27 01:49 UTC by chrisdavidson

Bug #247900
   https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=247900

printf.3
   Update order of parameters alphabetically
   Add parameter syntax to each parameter for clarity
   Untangle multiple option entries into individual entries
   Update sentence structure throughout
   Provide clarity on symbol based parameters

2024-03-27 02:20 UTC, chrisdavidson commented
I noticed another branch updates got put into this pull request. I am working on REMOVING the files associated with 4743e9f.

2024-03-27 10:27 UTC, dag-erling commented
The entries for the `B` and `b` conversion specifiers are incorrect, cf. https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2630.pdf

2024-03-27 11:19 UTC, chrisdavidson commented
> The entries for the `B` and `b` conversion specifiers are incorrect, cf. https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2630.pdf

The referenced document highlights unsigned int to unsigned binary conversion. It looks like the original manual page did not have this reference, i will update accordingly.

2024-03-27 11:31 UTC, dag-erling commented
> The referenced document highlights unsigned int to unsigned binary conversion. It looks like the original manual page did not have this reference, i will update accordingly.

You are mistaken, cf. 76edfabb.

2024-03-27 23:16 UTC, chrisdavidson commented
> > The referenced document highlights unsigned int to unsigned binary conversion. It looks like the original manual page did not have this reference, i will update accordingly.
> 
> You are mistaken, cf. [76edfab](https://github.com/freebsd/freebsd-src/commit/76edfabbecdec686a570b8e009d5ea4112f943e0).

I looked through that update and I must be missing something. 

The options b and B respectively are being described and when used with the x and X conversion parameters respectively they work as described. 

The updates conducted in this pull request are moving the elements to be more concise and easier to read. The changes that were conducted in August 2023, as referenced by the commit id above, are included in the baseline that the updates were based on, dated 05SEP2023.

2024-03-27 23:57 UTC, dag-erling commented
I am the author of both the commit in question and the code it documents. I assure you that I know what it is about. There is no such thing as “B and b options used with the X and x conversion parameters”. `X` and `x` are conversion _specifiers_, and so are `B` and `b`.

2024-03-28 01:07 UTC, chrisdavidson commented
okay, i will re-review and make appropriate changes.

beyond that, is there anything else that you thought was misaligned?

2024-04-19 18:40 UTC, bsdimp commented
generally this is great, let's get the issues resolved so we can commit.

2024-04-20 02:09 UTC, chrisdavidson commented
let me bring this back up.. the only issue i am aware of is the options mentioned? are there any other ones i should review?

2024-04-20 07:17 UTC, dag-erling commented
Yes, you have 48 lines ending in  a spurious `g`, you should revert to 4ecdab4 if you still have it.

2024-04-21 20:08 UTC, dag-erling commented
Now you have 48 lines ending in trailing whitespace.

2024-04-21 20:13 UTC, dag-erling commented
Chris, please, slow down. You just pushed a bunch of conflict markers.

2024-04-21 20:23 UTC, chrisdavidson commented
bah, sorry about this, my local git is pushing to here and NOT to my local branch.

2024-04-21 20:25 UTC, dag-erling requested changes

2024-04-21 20:25 UTC, dag-erling commented on lib/libc/stdio/printf.3
> +>>>>>>> 5affdd06c021 (Update order of parameters alphabetically)
conflict marker

2024-04-21 20:25 UTC, dag-erling commented on lib/libc/stdio/printf.3
> +A deprecate alias forg
```suggestion
A deprecated alias for
```

2024-04-21 20:25 UTC, dag-erling commented on lib/libc/stdio/printf.3
> +.It Cm p
Missing an entire section for `.It Cm o` here.

2024-04-21 20:25 UTC, dag-erling commented on lib/libc/stdio/printf.3
> +pointer argument is printed ing
trailing `g` again

2024-04-21 20:25 UTC, dag-erling commented on lib/libc/stdio/printf.3
> +conversions.
no

2024-04-21 20:25 UTC, dag-erling commented on lib/libc/stdio/printf.3
> +conversions.
no

2024-04-21 20:25 UTC, dag-erling commented on lib/libc/stdio/printf.3
> +.It Cm b
What about `argno`, `width`, `size` etc?

2024-04-21 20:25 UTC, dag-erling commented on lib/libc/stdio/printf.3
> +.It Cm B
What about `argno`, `width`, `size` etc?

2024-04-22 02:38 UTC, chrisdavidson commented
i'm working through how to get this all merged into one commit. I will update the comments section upon completion of this consolidation efforts.

2024-04-24 02:39 UTC, closed without merging

2024-04-24 02:41 UTC, chrisdavidson commented
I closed this pull request as the more i worked on it, the worse it got. I am going to review and generate a new pull request. Thank you for the input everyone.

2024-04-26 19:08 UTC, dag-erling commented
I'm sorry you feel that way, it seemed to be moving in the right direction.

2024-04-27 03:18 UTC, chrisdavidson commented
It is not the content i was struggling with, it was my poor attempt to consolidate all the changes into one commit and not cause the massive conflicts that were occurring, unintentionally. I took the necessary steps to diff the whole commit and made a new branch, the results of this updates are available here: https://github.com/freebsd/freebsd-src/pull/1200