dumpon: fix set but not used variable
freebsd/freebsd-src pull request #1178
Opened 2024-04-16 19:52 UTC by inkeliz

That is my attempt to fix one issue, when compiling with WITHOUT_OPENSSL or WITHOUT_CRYPTO:

```
/usr/home/x/freebsd/sbin/dumpon/dumpon.c:478:21: error: variable 'cipher' set but not used [-Werror,-Wunused-but-set-variable]
        int ch, error, fd, cipher
```

I'm not sure if that is the proper way to fix that.

2024-04-16 23:12 UTC, markjdb requested changes

2024-04-16 23:12 UTC, markjdb commented on sbin/dumpon/dumpon.c
> +	#endif
This should be removed, it won't compile.

2024-04-16 23:12 UTC, markjdb commented on sbin/dumpon/dumpon.c
> +	#ifdef HAVE_CRYPTO
Please keep `#ifdef` lines unindented.

2024-04-16 23:12 UTC, markjdb commented on sbin/dumpon/dumpon.c
> +		#endif
We should print a more useful error message here if `-C` isn't implemented. I suggest adding `errx(EX_USAGE, "built without crypto support, -C is unhandled");` or so.

2024-04-17 09:13 UTC, inkeliz commented
I think I fix that. However, while testing with `dumpon -C something`, it don't returns any error. Also, the `usage` didn't mention `-C` at all:

https://github.com/freebsd/freebsd-src/blob/7d03ec330684a4e82e6113df3f40305849e5fb6c/sbin/dumpon/dumpon.c#L74-L83

2024-04-17 13:40 UTC, markjdb commented
> I think I fix that. However, while testing with `dumpon -C something`, it don't returns any error.

The patch looks right. Are you sure you tested the right executable? What does dumpon print in this case?

> Also, the `usage` didn't mention `-C` at all:
> 
> https://github.com/freebsd/freebsd-src/blob/7d03ec330684a4e82e6113df3f40305849e5fb6c/sbin/dumpon/dumpon.c#L74-L83

That is a bug. I'd be happy to see a patch for that.

2024-04-17 15:22 UTC, markjdb approved these changes

2024-04-17 15:27 UTC, bsdimp commented on sbin/dumpon/dumpon.c
> +	int cipher;
I'd be tempted to just initialize here to safe 3 lines later

2024-04-17 15:28 UTC, markjdb reviewed
The commit's author name is "inkeliz@inkeliz.com", is it intentional? This is also the email address, so it looks strange.

2024-04-17 15:28 UTC, markjdb commented on sbin/dumpon/dumpon.c
> +			break;
I missed it earlier, but please use tabs for indentation, not spaces.

2024-04-17 15:28 UTC, bsdimp commented
I think this is good, possibly with the one tweak i suggested

2024-04-17 15:28 UTC, bsdimp commented
I can land

2024-04-18 15:35 UTC, markjdb approved these changes

2024-04-18 15:40 UTC, markjdb commented
Thank you for the patch.

2024-04-18 15:40 UTC, closed without merging