Replaced the usage of asctime with strftime
freebsd/freebsd-src pull request #1328
Opened 2024-07-16 21:14 UTC by AtariDreams

Replaced the usage of the obsolete asctime function with strftime for generating timestamp strings.

2024-07-29 19:40 UTC, bsdimp commented on usr.bin/at/at.c
> +	    strftime(time_string, sizeof(time_string), "Www Mmm dd hh:mm:ss yyyy\n", localtime(&timer));
This makes no sense. Did you test these changes? That's not a valid format string.

2024-07-29 19:41 UTC, bsdimp requested changes
Please use valid strftime strings.
And please provide proof that this is working the same before/after.

2024-07-29 22:13 UTC, concussious commented
Hi, I am a satisfied lock user. I use lock every single day. Thank you for your interest in lock. Please [don't break my heart](https://docs.freebsd.org/en/articles/committers-guide/#commit-log-message).

2024-07-30 19:19 UTC, jrtc27 commented
> Hi, I am a satisfied lock user. I use lock every single day. Thank you for your interest in lock. Please [don't break my heart](https://docs.freebsd.org/en/articles/committers-guide/#commit-log-message).

The first three sentences are spam. The final one links to some documentation that may be worth reading for the submitter, but the text used for the link is completely unrelated. This is extremely unhelpful and makes the entire message look like spam. Please do not do this again.

2024-07-30 21:53 UTC, concussious commented
Copy, sorry, thank you.

2024-09-13 03:00 UTC, closed without merging