lsvfs(1): Capsicumise
freebsd/freebsd-src pull request #1498
Opened 2024-10-27 15:10 UTC by kfv

2025-01-01 17:53 UTC, kfv commented
This must be ready, I believe.

Cc: @oshogbo

2025-01-02 11:36 UTC, oshogbo requested changes
We don't need to change Makefile to add casper support?

2025-01-02 11:41 UTC, oshogbo requested changes

2025-01-02 11:41 UTC, oshogbo commented on usr.bin/lsvfs/lsvfs.c
> +	if ((limit = cap_sysctl_limit_init(capsysctl)) == NULL)
We cannot check here for a NULL. As the non-casper version of the cap_sysctl_limit_init will return name as well. I guess we need to update man page for this (the return value section). The idea is that you ignore errors from `cap_sysctl_limit_init` ect, and verify only `cap_sysctl_limit`. See examples section of man page.

2025-01-02 11:43 UTC, kfv commented on usr.bin/lsvfs/lsvfs.c
> +	if ((limit = cap_sysctl_limit_init(capsysctl)) == NULL)
Alright, I'll take care of it now, and will also take care of the man page later today.

2025-01-02 11:43 UTC, kfv commented
> We don't need to change Makefile to add casper support?

You're right; I had changed it but forgot to commit. My apologies.

2025-01-02 11:44 UTC, oshogbo commented on usr.bin/lsvfs/lsvfs.c
> +	if ((limit = cap_sysctl_limit_init(capsysctl)) == NULL)
I guess we/I need to update the `cap_sysctl_limit_name` of the real function to ignore NULL limit.

2025-01-02 11:45 UTC, kfv commented on usr.bin/lsvfs/lsvfs.c
> +	if ((limit = cap_sysctl_limit_init(capsysctl)) == NULL)
Good idea, makes sense. Alright.

2025-01-02 11:50 UTC, kfv commented on usr.bin/lsvfs/lsvfs.c
> +	if ((limit = cap_sysctl_limit_init(capsysctl)) == NULL)
The latest commit should meet your call now. Let me know if any other change's required as well.

2025-01-08 12:54 UTC, oshogbo approved these changes

2025-01-19 16:44 UTC, asomers requested changes

2025-01-19 16:44 UTC, asomers commented on usr.bin/lsvfs/lsvfs.c
> +		err(EXIT_FAILURE, "unable to open system.sysctl servic");
```suggestion
		err(EXIT_FAILURE, "unable to open system.sysctl service");
```

2025-01-20 06:43 UTC, kfv commented on usr.bin/lsvfs/lsvfs.c
> +		err(EXIT_FAILURE, "unable to open system.sysctl servic");
Thanks for the catch! Resolved.

2025-01-20 15:43 UTC, asomers approved these changes

2025-06-12 00:31 UTC, bsdimp commented
@markjdb any final comments?

2025-08-04 19:22 UTC, bsdimp commented
@kfv Any comments? Otherwise, I plan on closing soon.

2025-08-04 22:58 UTC, kfv commented
Hi, apologies for the extended delay in addressing the requested changes. The past year has been personally and geopolitically challenging, and I appreciate your patience. I make sure to go through all the pending requests within the coming week at most. Thank you again for your understanding.

2025-08-05 14:32 UTC, kfv commented
@bsdimp, @markjdb: Hey! I believe it's now ready to ship.

2025-08-06 07:45 UTC, oshogbo commented on usr.bin/lsvfs/lsvfs.c
> +	for (int i = 0; i < (int)nitems(fl); i++) {
Instead of casting it to int maybe we can use `size_t` here?
What do you think?

2025-08-06 07:45 UTC, oshogbo commented on usr.bin/lsvfs/lsvfs.c
> +	cnt = buflen / sizeof(struct xvfsconf);
As we are here to do we want `cnt` keep as `int`?
We are dividing size_t by size_t, so potentially 64bits unsigned numbers and we store it in 32bit signed.

2025-08-06 08:56 UTC, kfv commented on usr.bin/lsvfs/lsvfs.c
> +	for (int i = 0; i < (int)nitems(fl); i++) {
Good catch — you're absolutely right. Thanks for pointing that out.

2025-08-06 08:56 UTC, kfv commented on usr.bin/lsvfs/lsvfs.c
> +	cnt = buflen / sizeof(struct xvfsconf);
Sharp eye — you're spot on, mate. Appreciate you flagging that.

2025-08-08 16:15 UTC, oshogbo commented on usr.bin/lsvfs/lsvfs.c
> +		for (size_t i = 0; i < cnt; i++) {
I think the indentation here is broken.

2025-08-08 19:49 UTC, kfv commented on usr.bin/lsvfs/lsvfs.c
> +		for (size_t i = 0; i < cnt; i++) {
I just checked – all looks fine. I only changed the initialisation clause; nothing else was modified.

2025-08-08 21:14 UTC, oshogbo commented on usr.bin/lsvfs/lsvfs.c
> +		for (size_t i = 0; i < cnt; i++) {
<img width="573" height="165" alt="image" src="https://github.com/user-attachments/assets/b5a32fc1-a936-47ed-aed0-b7a2c080efa3" />
Please verify commit:
 lsvfs(1): Make slight refactor

2025-08-08 21:18 UTC, kfv commented on usr.bin/lsvfs/lsvfs.c
> +		for (size_t i = 0; i < cnt; i++) {
All set – you've got my nod, mate.

2025-08-08 21:27 UTC, oshogbo commented on usr.bin/lsvfs/lsvfs.c
> +		for (size_t i = 0; i < cnt; i++) {
Sorry mate, but I think we are still not on the same page :)
In this PR you have two commits:
- e9e7ef72f28da5c3313b0b873ac1c9aba21d05fe: lsvfs(1): Make slight refactor
- 47757166ca6c4d48cf7e35eceb3dbded8c33d943: lsvfs(1): Capsicumise

In the first commit where you are doing a refactoring you are changing also the indentation. Here is the link:
https://github.com/freebsd/freebsd-src/commit/e9e7ef72f28da5c3313b0b873ac1c9aba21d05fe.patch

Here is the patch fragment:
```
+		for (size_t i = 0; i < cnt; i++) {
 		if (sysctlbyname("vfs.conflist", NULL, &buflen, NULL, 0) < 0)
-			err(1, "sysctl(vfs.conflist)");
-		xvfsp = malloc(buflen);
-		if (xvfsp == NULL)
-			errx(1, "malloc failed");
+			err(EXIT_FAILURE, "sysctl(vfs.conflist)");
+		if ((xvfsp = malloc(buflen)) == NULL)
+			errx(EXIT_FAILURE, "malloc failed");
 		if (sysctlbyname("vfs.conflist", xvfsp, &buflen, NULL, 0) < 0)
-			err(1, "sysctl(vfs.conflist)");
+			err(EXIT_FAILURE, "sysctl(vfs.conflist)");
 		cnt = buflen / sizeof(struct xvfsconf);
 
-		for (i = 0; i < cnt; i++) {
+		for (size_t i = 0; i < cnt; i++) {
 			printf(FMT, xvfsp[i].vfc_name, xvfsp[i].vfc_typenum,
 			    xvfsp[i].vfc_refcount,
 			    fmt_flags(xvfsp[i].vfc_flags));
``` 

This ends up with the wrong indentation of code:
<img width="1146" height="330" alt="image" src="https://github.com/user-attachments/assets/c70edc1b-2157-4010-8d99-5cf98ad32c3f" />

Only after applying the first patch.
Then when you apply the second patch you are fixing the indentation.

We don't need to change the indention in the first commit.

2025-08-08 21:30 UTC, kfv commented on usr.bin/lsvfs/lsvfs.c
> +		for (size_t i = 0; i < cnt; i++) {
Oh, my bad! We absolutely should not, indeed. Sorry, I checked but didn't notice (too sleepy ATM.) You're right. I'll fix it shortly.

2025-08-08 22:05 UTC, kfv commented on usr.bin/lsvfs/lsvfs.c
> +		for (size_t i = 0; i < cnt; i++) {
Apologies for the confusion earlier. While working on the latest domain iteration, I inadvertently copied and pasted the code above the conditionals, which caused the issue. I wasn't touching any indentation, it's likely that I accidentally used `yy` and `P` without realising. The issue has now been resolved.

2025-08-11 14:13 UTC, oshogbo commented on usr.bin/lsvfs/lsvfs.c
> +	if (sysctlbyname("vfs.conflist", NULL, &buflen, NULL, 0) < 0)
I was about to commit this change, when I have noticed one more thing. Sorry about that.

Do we want to always fetch the full list.
When we do:
```
lsvfs ufs
```

We don't need to fetch the `vfs.conflist` to check for UFS fs. Now we are adding a small overhead to the utility that we always fetch the list. @kfv what do you think?

2025-08-11 14:14 UTC, oshogbo commented
The first commit landed: a3eab01304884e13342bdaca4cf5204fa97ba456

2025-08-11 15:10 UTC, kfv commented on usr.bin/lsvfs/lsvfs.c
> +	if (sysctlbyname("vfs.conflist", NULL, &buflen, NULL, 0) < 0)
I’ll look into this in more detail and get back to you shortly.

2025-08-11 17:26 UTC, kfv commented on usr.bin/lsvfs/lsvfs.c
> +	if (sysctlbyname("vfs.conflist", NULL, &buflen, NULL, 0) < 0)
You are right. Resolved.

2025-08-11 17:28 UTC, kfv commented
@oshogbo: I’m pretty sure we’re finally ready to ship the Capsicumise commit as well. I’ve completely reworked it since it had some issues. Thanks a lot for catching that and for bearing with my slip-ups. It’s been a great journey!

2025-08-12 11:27 UTC, oshogbo commented on usr.bin/lsvfs/lsvfs.c
> +	if (caph_enter() != 0)
Sorry I don't like this new change.
After this change it seems like totally useless to enter Capability mode as we have done all the having lifting (parsing the list) in unsandboxed part. What we are sandboxing now? Just printing the names?

This is bad on my side as well because, I just now checked how the `getvfsbyname` works. It is overlook on my side. Sorry about that.

I think we should rewrite this. Maybe we can't use `getvfsbyname`. Maybe add a function to libc like: `getvfslist`. Reuse it in the `getvfsbyname` and use it here. Maybe we can split it like that:

```
list = getvfslist();
caph_enter();

// check for argv or print all list.
for (size_t i = 0; i < cnt; i++) {
      found = false;
      for (; argc > 0; argc--, argv++) {
         if (strcmp()) {
            found = true;
         }
      }
      if (found || argc == 0) {
         printf(...);
      }
}
```

Or just drop usage of `getvfsbyname` here without adding `getvfslist`.

2025-08-19 08:13 UTC, oshogbo commented
@kfv Thoughts?

2025-08-22 21:31 UTC, kfv commented on usr.bin/lsvfs/lsvfs.c
> +	if (caph_enter() != 0)
You’re right — and thanks a lot for pointing out. After moving the `getvfsbyname` calls outside capability mode, the code does indeed end up sandboxing only the printing phase, which weakens the whole point of Capsicum, agreed.

My intention with the change was to make the flow a bit clearer and avoid failures from `getvfsbyname` after entering capability mode. In that sense, it was a more workable version at the time, I still believe, even if not the right long-term solution.

Do I also agree with your suggestion: a `getvfslist`-style interface would be the right direction, so that we can fetch once and then enter capability mode before filtering/printing. I’ll start working on it shortly along those lines.

2025-08-22 21:51 UTC, kfv commented
@oshogbo: Reworked this based on your feedback (and also shared some thoughts on the thread). Sorry for the delay — I was away on vacation.

This version now fetches the full `vfs.conflist` list up front, then enters capability mode before any filtering/printing. That way sandboxing is meaningful, while keeping the overall approach close to what we had with `getvfsbyname`, but done manually here without further `sysctl` calls under the hood.

Could you take a look and let me know what you think?

2025-08-24 12:26 UTC, oshogbo commented
Yes, it looks much better. I will build it and test and let you know if it runs as expected.

2025-08-28 10:51 UTC, oshogbo commented
```
usr.bin/lsvfs/lsvfs.c:67:18: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
   67 |                         for (j = 0; j < argc; j++) {
      |                                     ~ ^ ~~~~
usr.bin/lsvfs/lsvfs.c:71:10: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
   71 |                         if (j == argc)
      |                             ~ ^  ~~~~
2 errors generated.
*** Error code 1
```

2025-08-30 09:18 UTC, kfv commented
Right, `j` should have been declared as `int` since it is compared against `argc`. My apologies for the oversight.

2025-10-06 15:31 UTC, oshogbo commented
Commited: a0c709ab5af4e87ce4579404c4ffbd4295ad12c5

2025-10-06 15:31 UTC, closed without merging