iwlwifi.4: bugs: tracking and clarification
freebsd/freebsd-src pull request #1541
Opened 2024-12-08 10:40 UTC by grahamperrin

Enhancements to the word 'certainly' might certainly include a link to at least one of the impressively well-organised tracking reports in Bugzilla.

2024-12-08 10:40 UTC, grahamperrin commented on share/man/man4/iwlwifi.4
> +blocks the LinuxKPI based wireless drivers tracking meta-bug
```suggestion
blocks the LinuxKPI-based wireless drivers tracking meta-bug
```

2024-12-08 10:41 UTC, grahamperrin commented on share/man/man4/iwlwifi.4
> +indirectly blocks the general wireless tracking meta-bug.
```suggestion
indirectly blocks the general wireless drivers tracking meta-bug.
```

For consistency with the preceding list item, add the word _drivers_.

2024-12-08 10:53 UTC, grahamperrin commented
Affects the _bugs_ section of **iwlwifi(4)**:

- <https://man.freebsd.org/cgi/man.cgi?query=iwlwifi&sektion=4&manpath=freebsd#BUGS>

I do always smile at the dryness of "Certainly." … equally, I am certain that a broad audience will positively appreciate the highly organised approach that is demonstrated by the trees of the tracking reports. 

----

@bzfbd

2025-08-04 19:27 UTC, bsdimp commented
@erikarn @bzfbd Can you two look at this and comment to see if this is still relevant or not?

2025-08-04 22:16 UTC, bzfbd commented
Half, I'll handle it

2025-08-05 00:00 UTC, bzfbd requested changes
Let me know what you think;  we can likely reduce it to three lines these days, which I do like as an experiment to see if it helps adding the bugzilla URL to the man page.

2025-08-05 00:00 UTC, bzfbd commented on share/man/man4/iwlwifi.4
> +.Pp
I believe this sections is overcome by events as the man page has been updated.
The suspend problem can be found in the list of bugs.

2025-08-05 00:00 UTC, bzfbd commented on share/man/man4/iwlwifi.4
> +.%U <https://bugs.freebsd.org/bugzilla/showdependencytree.cgi?id=iwlwifi&hide_resolved=1>
Can we simplify this to:
```
.%U <https://bugs.freebsd.org/bugzilla/showdependencytree.cgi?id=iwlwifi>
presents the known open and closed bugs related to
.Nm .
```
I do not think the entire bug tree is interesting to anyone here. If at best these links would go into the other respective man pages but then they are not entirely maintained as iwlwifi is so I am not sure.

2025-08-10 23:07 UTC, concussious commented on share/man/man4/iwlwifi.4
> +.%U <https://bugs.freebsd.org/bugzilla/showdependencytree.cgi?id=iwlwifi&hide_resolved=1>
Yes, we absolutely can, I would see how it looks (away from desk ATM) to take it even further like so:
```
.Lk https://bugs.freebsd.org/bugzilla/showdependencytree.cgi?id=iwlwifi Nm known bugs
```
Then, in graphical manual viewers, there would just be a clickable link that says "iwlwifi known bugs". Super forward compatible.

2025-08-19 23:23 UTC, bzfbd commented
The link to bugzilla for iwlwifi.4 is in.  Thank you for the idea!

I believe the other bits are either overcome by time or too much for here.

2025-08-19 23:23 UTC, closed without merging