savecore: add missing call to cap_openlog when in capabilities mode
freebsd/freebsd-src pull request #1546
Opened 2024-12-12 11:09 UTC by stephane-rochoy-stormshield

When run in capabilities mode, `savecore` seems to lack a call to `cap_openlog`. Notably it break the use of `LOG_PERROR`.

With the original one:

    $ /sbin/savecore -vC
    checking for kernel dump on device /dev/gpt/swapfs
    No dump exists

With the patched one:

    $ ./savecore -vC
    checking for kernel dump on device /dev/gpt/swapfs
    savecore 1424 - - /dev/gpt/swapfs: Permission denied
    No dump exists

2024-12-12 14:12 UTC, stephane-rochoy-stormshield commented
I'm looking to add a test as it should be trivial.

2024-12-12 15:39 UTC, emaste commented
Looks good. CC @oshogbo.

Also @bsdimp do we have advice on rebasing/squashing fixup commits in pull requests?

2024-12-12 16:05 UTC, stephane-rochoy-stormshield commented
> Looks good. CC @oshogbo.
> 
> Also @bsdimp do we have advice on rebasing/squashing fixup commits in pull requests?

Yes you have ;) I've put this PR in draft mode for now. I'll squash once ready. 
I'm discovering atf(7) and kyua(1) to add at least a basic test.

2024-12-12 16:10 UTC, emaste commented
Oh yes I didn't notice the Draft tag. The C change itself looks good :)

2024-12-12 19:57 UTC, bsdimp commented
git rebase -i main
squash all the tests into one commit and all the stuff in the actual binary into one. I think that's just the first one and all the rest squashed.

2024-12-13 07:24 UTC, oshogbo commented on sbin/savecore/tests/log_test.sh
> +  grep -qE 'savecore [0-9]+ - - /dev/missing: No such file or directory' savecore.err
I guess the indent is wrong here.

2024-12-13 07:24 UTC, oshogbo commented on sbin/savecore/tests/log_test.sh
> +  [ $? -eq 0 ] && atf_pass || atf_fail "missing/invalid error output"
Don't we want to use a regular if statement here to increase readability?

2024-12-13 08:25 UTC, stephane-rochoy-stormshield commented
Sorry for the initial noise. I cleaned the commits.

But one question remain about the test I propose to add: what is the proper way to test the instance of `savecore` from the installed build, i.e., not the one on the system? I find it convenient to `make world DESTDIR=…` but the tests don't seems to be aware of `$DESTDIR`.

2024-12-20 14:25 UTC, stephane-rochoy-stormshield commented
> But one question remain about the test I propose to add: what is the proper way to test the instance of `savecore` from the installed build, i.e., not the one on the system? I find it convenient to `make world DESTDIR=…` but the tests don't seems to be aware of `$DESTDIR`.

@oshogbo Do you have an opinion on this? Do you want me to just ignore `$DESTDIR`?

2025-01-07 07:13 UTC, stephane-rochoy-stormshield commented
Any news on this topic? Should I just call `savecore` instead of `${DESTDIR:-''}/sbin/savecore`?

2025-01-19 16:38 UTC, asomers commented
> Any news on this topic? Should I just call `savecore` instead of `${DESTDIR:-''}/sbin/savecore`?

Yes, you should do that.  The test suite is intended to run against an installed system.  There aren't any other tests tweaked to work with DESTDIR.  However, you can always alter PATH when running this test yourself.

2025-01-20 08:42 UTC, oshogbo approved these changes

2025-01-20 08:45 UTC, oshogbo commented
Sorry, for late response. LGTM.

2025-01-20 09:46 UTC, stephane-rochoy-stormshield commented
I adjusted copyright to 2025.

2025-01-20 15:55 UTC, asomers requested changes
While I don't dispute the results of your testing, I don't understand why it works.  Shouldn't it be sufficient to run openlog before cap_enter?  I don't understand why the program even needs cap_syslog in the first place.  IIUC, cap_syslog is only needed if you must open a syslog connection _after_ cap_enter.

2025-01-20 15:55 UTC, asomers commented on sbin/savecore/tests/log_test.sh
> +}
You don't need this cleanup, because Kyua always deletes the entire temporary PWD.  Also, this cleanup section wasn't even being invoked, since you don't have the cleanup keyword on line 7.
```suggestion
```

2025-01-21 07:22 UTC, stephane-rochoy-stormshield commented on sbin/savecore/tests/log_test.sh
> +}
Sorry, my bad. I removed the cleanup routine as suggested.

2025-01-21 07:38 UTC, stephane-rochoy-stormshield commented
> While I don't dispute the results of your testing, …

I'm just starting to discover this API so don't hesitate to dispute anything ;) 

> …  I don't understand why it works. Shouldn't it be sufficient to run openlog before cap_enter? I don't understand why the program even needs cap_syslog in the first place. IIUC, cap_syslog is only needed if you must open a syslog connection _after_ cap_enter.

I have to admit I didn't even try to move the call to `openlog` somewhere after `init_caps` because there's some calls to `logmsg` in between. IIUC, it would means calling `vsyslog` without `LOG_PERROR` which is not the intended behavior.

2025-01-21 17:06 UTC, asomers commented
> I have to admit I didn't even try to move the call to `openlog` somewhere after `init_caps` because there's some calls to `logmsg` in between. IIUC, it would means calling `vsyslog` without `LOG_PERROR` which is not the intended behavior.

Not after, before.  `openlog` ought to be called before `init_caps`, which it is.  However, `openlog` only affects future calls to `syslog` and `vsyslog`, not calls to `cap_syslog` and `cap_vsyslog`.  I'm wondering if logging will work perfectly if all of the `cap_syslog` stuff is removed, since `openlog` is already called early enough.

2025-01-22 14:21 UTC, asomers commented
It sounds like we can elminate cap_openlog/cap_syslog and go back to plain openlog/syslog, then.  Could you please do that?

2025-01-22 14:52 UTC, asomers commented
> @asomers Sorry, I'm just jumping in. It's not like syslog might want to reopen the file or connect again to `syslogd z(for example when the daemon was restarted)? Or `savecore`always log only to`stderr`?

Since savecore is a short-lived program, running for only a few seconds, I don't think we need to worry about syslogd restarts.  Are there any other reasons why syslog(3) might reconnect?

2025-01-22 14:59 UTC, oshogbo commented
Yeah, that's a valid point.
On the other hand, saving the core might take some time, as dumping a couple of GBs can be a time-consuming task.

I don't have a strong opinion on this.

I'm not sure what happens when the log file is rotated.

2025-01-22 15:05 UTC, markjdb commented
syslogd handles log rotation transparently to loggers. syslog(3) users don't need to reopen sockets after a log rotation. I can't see any reason not to use the plain syslog() and openlog() functions.

2025-01-22 15:06 UTC, stephane-rochoy-stormshield commented
> syslogd handles log rotation transparently to loggers. syslog(3) users don't need to reopen sockets after a log rotation. I can't see any reason not to use the plain syslog() and openlog() functions.

So the question is why do we have `cap_` variants for them exactly?

2025-01-22 15:10 UTC, asomers commented
> So the question is why do we have `cap_` variants for them exactly?

I think it was due to an oversight in d7fffd0689f1b18d1a3a589f113e41e53d72b547 .  The author replaced several other services with their capsicumized versions, where that's really needed.  I think he just didn't realize that the non-capsicum syslog would work fine.

2025-01-22 15:23 UTC, markjdb commented
> > So the question is why do we have `cap_` variants for them exactly?
> 
> I think it was due to an oversight in [d7fffd0](https://github.com/freebsd/freebsd-src/commit/d7fffd0689f1b18d1a3a589f113e41e53d72b547) . The author replaced several other services with their capsicumized versions, where that's really needed. I think he just didn't realize that the non-capsicum syslog would work fine.

Yes, I think it was probably me being overlay paranoid.

As was already noted, savecore is a short-lived program, it's unlikely that it'll hit the conditions under which syslog(3) needs to reconnect (syslogd restarts, or its logging buffer is full). So, plain openlog()+syslog() should work fine in practice.

OTOH, I suspect the patch in this PR is also fine as-is. Maybe let's merge it and consider removing cap_syslog separately, given that we're just trying to fix a simple bug here? Either approach is ok with me.

2025-01-23 07:35 UTC, stephane-rochoy-stormshield commented
So the short-term plan is to add the missing call to `cap_openlog` to fix `savecore`'s behavior regarding `LOG_PERROR`.

But I'm not sure to understand the long-term plan: is it to just drop the use of `cap_openlog` and `cap_vsyslog`? Is looks like dropping the Casper's `system.syslog` service so could someone explain the purpose of this service in the first place?

2025-01-23 14:10 UTC, markjdb commented
> So the short-term plan is to add the missing call to `cap_openlog` to fix `savecore`'s behavior regarding `LOG_PERROR`.
> 
> But I'm not sure to understand the long-term plan: is it to just drop the use of `cap_openlog` and `cap_vsyslog`? Is looks like dropping the Casper's `system.syslog` service so could someone explain the purpose of this service in the first place?

It's to handle the rare case where syslog(3) has to reconnect to syslogd's socket. In capability mode, connect() is not allowed, so we use a casper service. This is mostly suitable for long-running programs, where the likelihood of needing to reconnect at some point is high.

I tend to think that syslog(3) could instead just open /var/run (limiting rights to CAP_CONNECTAT, CAP_LOOKUP, CAP_WRITE, ...?) and use connectat(2) when needed. @oshogbo do you see any problem with this alternative? It means that we hold an extra capability for /var/run, but I think that's a small downside.

2025-01-24 19:00 UTC, markjdb commented
Merged, thank you.

2025-01-24 19:00 UTC, closed without merging