smbfs(4): evaluate filesystems/smbnetfs
freebsd/freebsd-src pull request #1562
Opened 2024-12-27 10:16 UTC by grahamperrin

RIP sysutils/fusefs-smbnetfs, one of 142 moves that arose from
https://github.com/freebsd/freebsd-ports/pull/302 and base 6e2da9672f79
on 2024-11-06. This one involved a change of name in addition to the
change of category.

Instead, advise users to evaluate filesystems/smbnetfs.

MFC after:      1 week

2024-12-27 10:17 UTC, grahamperrin commented
Plain text, with line breaks: 

```text
RIP sysutils/fusefs-smbnetfs, one of 142 moves that arose from
https://github.com/freebsd/freebsd-ports/pull/302 and base 6e2da9672f79
on 2024-11-06. This one involved a change of name in addition to the
change of category.

Instead, advise users to evaluate filesystems/smbnetfs.

MFC after:      1 week
```

2024-12-27 10:23 UTC, grahamperrin commented
Sorry, I made a mistake in the commit log message at [`9029293` (#1562)](https://github.com/freebsd/freebsd-src/pull/1562/commits/90292937e200113dd42a4c26918d8b20d0873148):

> base

– should have been: 

> ports

2024-12-27 10:37 UTC, grahamperrin commented
The September PR in ports: 

- https://github.com/freebsd/freebsd-ports/pull/302

The 2024-11-06 commit: 

- [filesystems: add new category for file systems and related utilities · freebsd/freebsd-ports@6e2da96](https://github.com/freebsd/freebsd-ports/commit/6e2da9672f79f44048d597f0f61e4646cdeade9d)
- <https://cgit.freebsd.org/ports/commit/?id=6e2da9672f79f44048d597f0f61e4646cdeade9d>

2024-12-27 11:04 UTC, grahamperrin commented
From <https://github.com/freebsd/freebsd-ports/pull/302#issuecomment-2472026605> (2024-11-13): 

> … This change hasn't even hit quarterly yet.

The suggested one-week MFC here (Friday 27th December, looking to Thursday 2nd January) is, partly, an allowance for the change in ports to reach quarterly.

2024-12-30 10:06 UTC, concussious approved these changes

2024-12-30 15:28 UTC, asomers approved these changes

2025-01-06 17:37 UTC, concussious commented
This could use a better commit message. I only just now realized exactly what happened. Suggest something like:
 
```
smbfs.4: Update smbnetfs location

A new "filesystems" ports category has been created, and all filesystem ports have been moved there. Update the smbfs manual to point to the new location.

MFC after:    3 days
```

2025-01-06 17:43 UTC, concussious requested changes
Sorry to back track, but I only just now realized *why* this is going on.

This could use a better commit message to make that more obvious. Suggest something like:
```
smbfs.4: Update smbnetfs location

A new "filesystems" ports category has been created,
and all filesystem ports have been moved there.
Update the smbfs manual to point to the new location.

Fixes:        ports#short-commit-hash(Commit title)
MFC after:    3 days
```
Key points: the .4 instead of (4) shows you're talking about the manual, not the driver itself.

The description explains why this change is happening without needing to follow links. 

Additionally, but not my call, it's vastly preferred that everything in src/ effected by this should be one commit.

Thanks!

2025-01-10 12:21 UTC, concussious commented
This can be closed, I did all the fallout in the src tree in one commit here [^1].

I'm about 1/3rd of the way through doing the same in the doc tree.

[^1]: https://reviews.freebsd.org/D48406

2025-05-05 05:21 UTC, bsdimp commented
already in, per Zaiee...  and verified that when then is appled, only .Dd is changed.

2025-05-05 05:21 UTC, closed without merging