bhyve: enhance debug info for memory range clash
freebsd/freebsd-src pull request #463
Opened 2021-04-13 23:00 UTC by RobCrowston

Explain what the two clashing regions are.

2021-04-26 23:32 UTC, jake-87 commented
Are we sure that that "claimed" is the right wording? I would lean more towards "reserved", as that seems to be a more accurate description of the message.

2021-04-26 23:45 UTC, jake-87 requested changes
Reword section for clariry

2021-04-26 23:45 UTC, jake-87 commented on usr.sbin/bhyve/mem.c
> +		       "claims region already claimed for '%s'\n",
Reword to "claims region already reserved for"

2021-06-13 22:45 UTC, bsdimp commented
This was approved in https://reviews.freebsd.org/D29696 and I landed as efec757b2042

2021-06-13 22:45 UTC, closed without merging