Fix SHA512_224_Final() on little-endian machines
freebsd/freebsd-src pull request #635
Opened 2023-01-04 07:45 UTC by sebhub

We have

  #define SHA512_224_DIGEST_LENGTH 28

which is not a multiple of 8.

So, for little-endian machines the following code does not work, since the last 32-bits of the digest are not encoded:

static void
be64enc_vect(unsigned char *dst, const uint64_t *src, size_t len) {
        size_t i;

        for (i = 0; i < len / 8; i++)
                be64enc(dst + i * 8, src[i]);
}

Use be32enc() if len is not a multiple of eight.

PR: 266863

2023-01-09 19:04 UTC, emaste commented
Ping @cperciva

2023-01-10 20:44 UTC, cperciva commented
This looks like it's an @allanjude bug -- he added the truncated SHA512s in 1780e407158ada85e454b24960b83a4f8e35cc25.  In addition to fixing the bug we should have tests for SHA512/224... and also audit the tree to see if anything is currently using it.  We don't want to make people lose data if e.g. a broken SHA512/224 was used in ZFS somewhere.

2023-01-10 21:24 UTC, allanjude approved these changes
Reviewed-by: allanjude

2023-01-11 06:07 UTC, sebhub commented
The error showed up in some very basic tests for RTEMS which uses a port of the FreeBSD source files:

https://github.com/RTEMS/rtems/blob/master/testsuites/libtests/sha/init.c

2023-01-30 10:05 UTC, sebhub commented
Is there anything required from my side to get this integrated?

2023-01-30 14:14 UTC, bsdimp commented
The zfs issue and audit is why I didn't land this.

2023-01-30 15:24 UTC, cperciva commented
Yeah, I'll be taking care of this but I want to be careful to make sure I don't break anyone's system in the process.  Don't worry, I haven't forgotten.

2023-01-30 19:02 UTC, allanjude commented
ZFS only uses SHA512t256, not 224, so it should not have recorded any incorrect hashes to disk

2023-02-03 15:00 UTC, dag-erling requested changes

2023-02-03 15:05 UTC, sebhub commented on sys/crypto/sha2/sha512c.c
>   */
I changed the comment because the code is right and the comment was wrong.

2023-02-03 15:13 UTC, dag-erling commented on sys/crypto/sha2/sha512c.c
>   */
My apologies, I see that you in fact corrected a mistake in the original comment.

I still think we should add `inline` and assertions. I will post a Phabricator review.

2023-02-03 15:22 UTC, dag-erling commented
Continued in https://reviews.freebsd.org/D38372

2023-02-03 15:22 UTC, closed without merging