Daemon improvements
freebsd/freebsd-src pull request #667
Opened 2023-02-24 22:49 UTC by ngortheone

Code readability and consistency improvements

2023-02-24 23:17 UTC, igalic requested changes
this (a46e046) is, unfortunately, running counter to our style(9) definition

2023-02-25 01:19 UTC, kevans91 commented
I don't think I understand the last one; daemon shouldn't be running forever in the non-forking mode, it just doesn't need to monitor the spawned process so it jumps right into `execvp`  (note that `pid` will not be reassigned from -1 if none of these options are set).

2023-02-25 01:19 UTC, kevans91 commented on usr.sbin/daemon/daemon.c
> +	int outfd = open_log(lpp->outfn);
This one's a no-go, declarations must be at the top of the containing block.

2023-02-25 01:19 UTC, kevans91 commented on usr.sbin/daemon/daemon.c
> +        sigset_t mask_susp;
Same comment as below about declarations

2023-02-25 01:19 UTC, kevans91 commented on usr.sbin/daemon/daemon.c
> +        struct log_params logpar = { 0 };
Same comment as below about declarations

2023-02-25 01:19 UTC, kevans91 commented on usr.sbin/daemon/daemon.c
> -		struct sigaction act_term, act_chld, act_hup;
I have mixed feelings about this one, given that they're really only used within this block

2023-02-25 02:07 UTC, ngortheone commented
@kevans91 disregard my last commit, I misinterpreted the code a bit. I will revert it soon.
But it does leave a big question open, which I will share in email

2023-02-25 16:09 UTC, closed without merging