zfsd: Add hotplug support for spare vdevs
freebsd/freebsd-src pull request #697
Opened 2023-03-20 11:52 UTC by ixhamza

This commit adds support for the spare vdev hotplug. Currently, spare vdevs do not become Online automatically when reinserted due to the absence of Pool GUID. This is also to make zfsd functionality align with the linux zed daemon. Linux zed PR: https://github.com/openzfs/zfs/pull/14295

2023-03-20 11:52 UTC, ixhamza commented
cc: @amotin

2023-03-22 16:49 UTC, asomers commented
Could you please describe in more detail what this change does?  Does it simply online a spare that gets temporarily removed?  Or does it use autoreplace to replace a removed space with a newly inserted blank HDD?  Does it only affect spares that are not in use, or spares that are in use as well?  Have you run the tests in tests/sys/cddl/zfs/tests/zfsd ?

2023-03-22 19:29 UTC, asomers commented
To run those tests, you need to edit /etc/kyua/kyua.conf and set the `test_suites.FreeBSD.disks` variable to a space separated list of disks for the tests, like "/dev/da0 /dev/da1 /dev/da2" etc.  Don't use any disks you care about, of course!  Best if you have at least five disks.  Otherwise some will be skipped.

2023-03-23 23:34 UTC, ixhamza commented
Thank you @asomers. I was able to run the tests with and without my patch and the success rate was the same, i.e., the same tests were failing in both scenarios:
```
root@freebsd-s:/usr/tests/sys/cddl/zfs/tests/zfsd # kyua test -k Kyuafile
zfsd_test:zfsd_autoreplace_001_neg  ->  failed: Testcase failed  [1.323s]
zfsd_test:zfsd_autoreplace_002_pos  ->  failed: Testcase failed  [23.062s]
zfsd_test:zfsd_autoreplace_003_pos  ->  failed: Testcase failed  [23.124s]
zfsd_test:zfsd_degrade_001_pos  ->  failed: Testcase failed  [67.929s]
zfsd_test:zfsd_degrade_002_pos  ->  expected_failure: https://www.illumos.org/issues/8614 Checksum errors on a mirrored child of a raidz are incorrectly accounted: Testcase failed  [74.160s]
zfsd_test:zfsd_fault_001_pos  ->  failed: Testcase failed  [0.297s]
zfsd_test:zfsd_hotspare_001_pos  ->  passed  [69.773s]
zfsd_test:zfsd_hotspare_002_pos  ->  passed  [42.481s]
zfsd_test:zfsd_hotspare_003_pos  ->  passed  [47.814s]
zfsd_test:zfsd_hotspare_004_pos  ->  passed  [25.555s]
zfsd_test:zfsd_hotspare_005_pos  ->  failed: Testcase failed  [63.433s]
zfsd_test:zfsd_hotspare_006_pos  ->  passed  [92.677s]
zfsd_test:zfsd_hotspare_007_pos  ->  passed  [43.115s]
zfsd_test:zfsd_hotspare_008_neg  ->  failed: Testcase failed  [69.873s]
zfsd_test:zfsd_import_001_pos  ->  failed: Testcase failed  [25.885s]
zfsd_test:zfsd_replace_001_pos  ->  passed  [4.704s]
zfsd_test:zfsd_replace_002_pos  ->  expected_failure: Not yet implemented in zfsd: Testcase failed  [0.212s]
zfsd_test:zfsd_replace_003_pos  ->  passed  [20.258s]

Results file id is usr_tests_sys_cddl_zfs_tests_zfsd.20230323-182814-414048
Results saved to /root/.kyua/store/results.usr_tests_sys_cddl_zfs_tests_zfsd.20230323-182814-414048.db

10/18 passed (8 failed)
```
[results.usr_tests_sys_cddl_zfs_tests_zfsd.20230323-182814-414048.zip](https://github.com/freebsd/freebsd-src/files/11057198/results.usr_tests_sys_cddl_zfs_tests_zfsd.20230323-182814-414048.zip)

2023-03-24 10:59 UTC, ixhamza commented
Thanks, @asomers. The report shows that test cases are failing due to the following reasons:
```
zfsd_autoreplace_001_neg: ERROR: check_state testpool.2366 /dev/nvd0 ONLINE unexpectedly exited 0
zfsd_autoreplace_002_pos: ERROR: Disk /dev/nvd4 not marked as ONLINE in testpool.2391
zfsd_autoreplace_003_pos: ERROR: Disk /dev/nvd3 not marked as ONLINE in testpool.2392
zfsd_degrade_001_pos: ERROR: Disk /tmp/kyua.QwpiHu/5/work/file1.1933 not marked as DEGRADED in testpool.1933
zfsd_fault_001_pos: sysctl: unknown oid 'kern.cam.da..error_inject'
zfsd_hotspare_005_pos: ERROR: check_state testpool.2091 /tmp/kyua.QwpiHu/12/work/hotspare_tmpdir/file.0 INUSE exited 1
zfsd_hotspare_008_neg: ERROR: /sbin/zpool add testpool.2070 spare /dev/nvd3 exited 1
zfsd_import_001_pos: ERROR: Disk AVAIL not marked as  in testpool.1884
```
I have also attached [html.tar.gz](https://github.com/freebsd/freebsd-src/files/11061264/html.tar.gz) if you want to take a look. But interestingly, behavior is similar if I revert this commit. I am using five Qemu NVME disks for testing.

2023-04-03 17:20 UTC, ixhamza commented
Hello @asomers, just a polite reminder about this pull request. Would you be able to take a look when you have a moment? Thanks!

2023-04-03 17:34 UTC, asomers commented
Actually, I'm working on it at this very moment.  But first I'm trying to fix a few issues that I've identified in the existing tests.

2023-04-03 17:35 UTC, ixhamza commented
Thanks a lot, @asomers.

2023-04-05 20:29 UTC, asomers requested changes
It LGTM!  Apart from the inline comments, that is.  I made some new test cases, too.

2023-04-05 21:40 UTC, ixhamza commented on cddl/usr.sbin/zfsd/vdev.cc
> +	(void) VdevLookupPoolGuid();
Sorry, My bad. I guess that's a leftover but not required now. I have removed it.

2023-04-05 21:43 UTC, ixhamza commented on sys/contrib/openzfs/module/zfs/spa.c
> +			VERIFY0(nvlist_lookup_uint64_array(spares[i],
Yes. It's already merged in the openzfs master and 2.1.10 staging.
https://github.com/openzfs/zfs/pull/14653
https://github.com/openzfs/zfs/pull/14672

2023-04-06 17:51 UTC, asomers approved these changes

2023-04-06 18:01 UTC, asomers commented
Thanks for your submission, Ameer!  BTW, have you checked whether autoreplace by physical path works for spares?  I'm guessing that it doesn't.  Are you going to work on that?

2023-04-06 18:01 UTC, closed without merging

2023-04-06 19:22 UTC, ixhamza commented
@asomers - Sorry but I did not fully understand what you meant by `autoreplace by physical path`. If you could please let me know a scenario that you think should work but does not, I can work on that to fix it.

2023-04-06 19:27 UTC, asomers commented
What I mean is on a server with a SES backplane, if you remove an unused spare and then replace it by a different disk of the same model in the same slot, and the pool has the `autoreplace` property set, will the new disk join the pool as a spare?  That works with regular vdevs, but I'm not sure about spares.

2023-04-06 19:43 UTC, ixhamza commented
You are right, ```autoreplace``` property is not supported out of the box for spare vdevs. Thanks for bringing it up. I will try to make it work in the future patch for both zed and zfsd daemons.

2023-04-06 19:57 UTC, ixhamza commented
By the way, I just quickly tested with QEMU-emulated nvme disks, and ```autoreplace``` property does not seem to work for normal vdevs also, if I am testing it correctly. I created a single two-way mirror with autoreplace property on ```zpool create -f -o autoreplace=on tank mirror nvd0 nvd1```. Then removed nvd1 to replace it with a blank nvd1 (Can see a new nvd1 added in /dev/ entry) but the zpool status still shows nvd1 as removed.
```
	NAME        STATE     READ WRITE CKSUM
	tank        DEGRADED     0     0     0
	  mirror-0  DEGRADED     0     0     0
	    nvd0    ONLINE       0     0     0
	    nvd1    REMOVED      0     0     0
```

2023-04-06 20:06 UTC, ixhamza commented
It could also be related to the QEMU-emulated disks though I am keeping the serial same for both disks. Unfortunately, don't have real hot-pluggable disks available right now to test it.

2023-04-06 20:07 UTC, asomers commented
That's because autoreplace requires the disk's physical path attribute to be set.  Without that attribute, it has no way of knowing which disk is in which slot.  The only way to get a physical path is to use a disk in a SES enclosure, or to use gnop(8).

2023-04-06 20:09 UTC, ixhamza commented
Ah, right. Thank you. I will test it accordingly for spares.