BUG: strncmp only checks for the first 5 letters of "Driver", not all 6.
freebsd/freebsd-src pull request #738
Opened 2023-05-08 21:49 UTC by AtariDreams

As a result, it is only really checking for the word Drive, making "Drive" appended to anything else considered for efi env.

2023-05-09 17:32 UTC, delphij requested changes
Hi, nice find!  To make the code more readable, could you please change the length numbers to `strlen()`s instead?  (I am pretty sure that the compiler would turn these into number constants at build time).

2023-05-18 17:44 UTC, bsdimp commented
Looks good to me... The practical effect of this, however, is limited since we'd filter more things through this gate, but nothing standard conflicts... It's a good fix, and I'll land it.

2023-05-18 17:46 UTC, bsdimp commented
So I can't find the name/email that I've used in the past to land your commits, and this commit has the 'github' anonymous email address.

2023-05-18 17:47 UTC, bsdimp commented
Oh, wait, in the past I've used
Author: Alfonso <gfunni234@gmail.com>
is that still good?

2023-05-19 14:34 UTC, AtariDreams commented
> Oh, wait, in the past I've used Author: Alfonso [gfunni234@gmail.com](mailto:gfunni234@gmail.com) is that still good?

This is still good.

2023-05-19 14:34 UTC, AtariDreams commented
@bsdimp

2023-06-07 00:11 UTC, ngie-eign commented
Please change the email address to a non-users.noreply.github.com based address.
If you use `git config user.email`, etc, then run `git commit --reset-author --amend`, it will update the authorship appropriately.

2023-06-11 18:13 UTC, AtariDreams commented
> Please change the email address to a non-users.noreply.github.com based address. If you use `git config user.email`, etc, then run `git commit --reset-author --amend`, it will update the authorship appropriately.

Done!

2023-06-23 03:33 UTC, kevans91 commented
Merged as 39ae24e3bf1c8e7d053d0249a6bc88f65eff6de1. Thanks!

2023-06-23 03:33 UTC, closed without merging