Update OpenSSL to version 3.0.8 in the base system
freebsd/freebsd-src pull request #740
Opened 2023-05-11 04:22 UTC by khorben

This branch is the closest I am currently to a functional update to OpenSSL 3.0.8 in FreeBSD's base system. It was started from the existing `vendor/openssl-3.0` branch.
The thorough review expected should include:
* Security patches up to date (the corresponding `security/openssl30` port fixes CVEs, I have not included them yet)
* Other patches in the corresponding port may be relevant too (I have not included them)
* API changes reflected accurately in `secure/lib/libcrypto/Version.map` and `secure/lib/libssl/Version.map`
* Whether the choice of `SHLIB_MAJOR` is good (currently `30` since `3` is already obsolete)
* Functional tests on Tier-1 architectures (amd64, aarch64...)
* Relevance of the `ossl-modules` providers
* Patches to software using OpenSSL are correct (especially libradius)
* The included update of ldns is correct (from the `vendor/ldns-1.8.3` tag by YT)
In most software users of OpenSSL, a compatibility compilation flag was used in order to expose and use the former OpenSSL API.

Sponsored by: FreeBSD Foundation

2023-05-11 04:33 UTC, ngie-eign commented
@khorben : you're awesome! Would you be opposed to me taking bits of your work, cherry-picking/squashing them, then pushing bits and pieces into base?

2023-05-11 04:34 UTC, ngie-eign commented
My brain cells have been under stimulated lately. I'd really like to do some straightforward FreeBSD development.

2023-05-11 04:35 UTC, ngie-eign commented
Hmm.. the build failed with amd64. Let's see if I can track down why and propose a change in the PR.

2023-05-11 04:36 UTC, khorben commented
> @khorben : you're awesome! Would you be opposed to me taking bits of your work, cherry-picking/squashing them, then pushing bits and pieces into base?

This is great to hear and absolutely, feel free to sort it out and clear the way :)
I tried to keep the commit history relatively clean, I just couldn't put all of the relevant changes directly in the merge commit.

2023-05-11 04:40 UTC, khorben commented
> Hmm.. the build failed with amd64. Let's see if I can track down why and propose a change in the PR.

Classic, I forgot to `git add` a file; I have updated the branch.

2023-05-11 14:32 UTC, emaste commented
@ngie-eign I think all of the `CFLAGS+=-DOPENSSL_API_COMPAT=0x10100000L` additions should be good to go now.

I used "specify OpenSSL 1.1 API" instead of "fix building with OpenSSL 3.0" in the commit message subjects, and these commits should have a `Sponsored by: The FreeBSD Foundation`.

2023-05-11 14:48 UTC, emaste commented
Hmm, dma fails with `OPENSSL_API_COMPAT` set, with:

```
/usr/home/emaste/src/freebsd-git/main/contrib/dma/crypto.c:118:2: error: call to undeclared function 'SSL_library_init'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
        SSL_library_init();
        ^
/usr/home/emaste/src/freebsd-git/main/contrib/dma/crypto.c:119:2: error: call to undeclared function 'SSL_load_error_strings'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
        SSL_load_error_strings();
        ^
/usr/home/emaste/src/freebsd-git/main/contrib/dma/crypto.c:119:2: note: did you mean 'ERR_lib_error_string'?
/usr/include/openssl/err.h:239:13: note: 'ERR_lib_error_string' declared here
const char *ERR_lib_error_string(unsigned long e);
            ^
2 errors generated.
```

Indeed,
> The SSL_library_init() and OpenSSL_add_ssl_algorithms() functions were deprecated in OpenSSL 1.1.0 by OPENSSL_init_ssl().

so IMO we should update dma and add the `OPENSSL_API_COMPAT` #define first

2023-05-11 21:15 UTC, ngie-eign commented on lib/libfido2/Makefile
> +CFLAGS+= -DOPENSSL_API_COMPAT=0x10100000L
Does updating libfido2 fix this issue?

2023-05-11 21:17 UTC, ngie-eign commented
> Hmm, dma fails with `OPENSSL_API_COMPAT` set, with:
> 
> ```
> /usr/home/emaste/src/freebsd-git/main/contrib/dma/crypto.c:118:2: error: call to undeclared function 'SSL_library_init'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
>         SSL_library_init();
>         ^
> /usr/home/emaste/src/freebsd-git/main/contrib/dma/crypto.c:119:2: error: call to undeclared function 'SSL_load_error_strings'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
>         SSL_load_error_strings();
>         ^
> /usr/home/emaste/src/freebsd-git/main/contrib/dma/crypto.c:119:2: note: did you mean 'ERR_lib_error_string'?
> /usr/include/openssl/err.h:239:13: note: 'ERR_lib_error_string' declared here
> const char *ERR_lib_error_string(unsigned long e);
>             ^
> 2 errors generated.
> ```
> 
> Indeed,
> 
> > The SSL_library_init() and OpenSSL_add_ssl_algorithms() functions were deprecated in OpenSSL 1.1.0 by OPENSSL_init_ssl().
> 
> so IMO we should update dma and add the `OPENSSL_API_COMPAT` #define first

Approved internal change for merge with FreeBSD.
I provided a complete patch upstream to https://github.com/corecode/dma/pull/126 to leverage the OpenSSL 3 APIs if/when possible.

2023-05-11 22:37 UTC, emaste commented on lib/libfido2/Makefile
> +CFLAGS+= -DOPENSSL_API_COMPAT=0x10100000L
libfido2's upstream build does:
```
        if(CRYPTO_VERSION VERSION_GREATER_EQUAL 3.0)
                add_definitions(-DOPENSSL_API_COMPAT=0x10100000L)
        endif()
```
with a few special case `#if OPENSSL_VERSION_NUMBER >= 0x30000000` here and there, but I imagine a future update will address this.

2023-05-13 01:44 UTC, ngie-eign reviewed
Submitted upstream as https://github.com/libarchive/libarchive/pull/1869 .

2023-05-13 02:03 UTC, ngie-eign commented on lib/libarchive/Makefile.inc
> +LIBADD+=	ssl crypto
Following up on my comment... libssl should not be required here. None of the libssl-related APIs are used in libarchive.
My guess is that this change was made based on similar code in the upstream pkg-config. I submitted https://github.com/libarchive/libarchive/pull/1870 to correct the overlinking.

2023-05-13 03:24 UTC, ngie-eign reviewed
Review: https://reviews.freebsd.org/D40082

2023-05-13 03:29 UTC, ngie-eign requested changes
This isn't right. libmd and libcrypto shouldn't be mixed.

2023-05-13 03:31 UTC, ngie-eign commented
> This isn't right. libmd and libcrypto shouldn't be mixed.

To be clear (because my last statement wasn't potentially): the implementations *can* mix by design, but there's no reason why there should be 2 crypto implementations linked into a library.

This effectively overlinks libmd into libfetch when MK_OPENSSL != no.

2023-05-20 18:43 UTC, ngie-eign reviewed
The lib/ldns change was submitted as c6750ddec9177b67bb4883717933e87ac24a3a44.

2023-05-20 19:08 UTC, ngie-eign commented
> > Review: https://reviews.freebsd.org/D40082
> 
> The lib/ldns change was submitted as c6750ddec9177b67bb4883717933e87ac24a3a44.

The above commit broke the build; I reverted it in 902dc544cc5859e24c727126e45416133c1c6d46.

This is something that will likely need to come in as part of the entire OpenSSL 3.0 deliverable, or adjusted to work with main, as shipped today.

2023-05-20 19:12 UTC, emaste commented
> > > Review: https://reviews.freebsd.org/D40082
> > 
> > 
> > The lib/ldns change was submitted as [c6750dd](https://github.com/freebsd/freebsd-src/commit/c6750ddec9177b67bb4883717933e87ac24a3a44).
> 
> The above commit broke the build; I reverted it in [902dc54](https://github.com/freebsd/freebsd-src/commit/902dc544cc5859e24c727126e45416133c1c6d46).

This is perhaps the same sort of issue we encountered with dma, but a more involved example?

2023-05-26 22:10 UTC, khorben commented
I have now marked this PR as "ready", with the following to keep in mind:
* The configuration applied is as per the `security/openssl30` port, with the legacy provider enabled
* This is strictly the 3.0.8 release, security patches issued since that release are ___not___ included; the CVE fixes found in the `security/openssl30` port are ___not___ included here (they probably deserve their own respective commits in order to keep track)
* Other patches in the corresponding port may be relevant too (I have not included them)
* I believe the API changes to be reflected accurately in `secure/lib/libcrypto/Version.map` and `secure/lib/libssl/Version.map`
* The choice of `SHLIB_MAJOR` is `3` in OpenSSL's header files (as per upstream) but `30` for the `.so` files (since `.3` has already been used by FreeBSD before in base)
* The following architectures are believed to build: amd64, aarch64, i386
* The `ossl-modules` providers have not been tested yet
* This does not touch the OpenSSL files that were moved in bc3d5698008e9b3b19495e853cbc2598979ccf8a into `sys/crypto/openssl` to avoid any trouble with the kernel, and re-imports them into `crypto/openssl` instead; security fixes beware of both locations
* The assembly files for amd64, i386, aarch64 were obtained by cross-compiling the original archive from source instead of with `Makefile.asm`

2023-05-26 23:37 UTC, emaste commented
cc @bsdjhb

2023-05-31 04:56 UTC, khorben commented
Unfortunately this pull-up request has to go back to draft after the update to 1.1.1u in `main`.

2023-06-01 18:07 UTC, khorben commented
Closing this pull-up request now that the direct update to OpenSSL 3.0.9 is almost ready.

2023-06-01 18:07 UTC, closed without merging