hwpmc(4): instead of manual edition, use sysrc(8)
freebsd/freebsd-src pull request #785
Opened 2023-06-29 06:20 UTC by grahamperrin

Exemplifying safe use of sysrc(8) has become commonplace in documentation such as the FreeBSD Handbook.

2023-06-29 06:28 UTC, grahamperrin commented
Compare with, for example: 

* https://github.com/freebsd/freebsd-src/commit/3048255235c13ee10b5110350ab5dde9d619ccd1#diff-976f016607a684dfe4b478a32cab7f63888567c6c6dc52bd7ac0babc147d3054R17
* https://github.com/freebsd/freebsd-src/commit/3a498c2e8a70ecdf8a3f5f033311793796f0d398#diff-78e94bf64d2cc067b3e7121371db07198e55ec8a7833298002dff1496679c7f3R4107
* https://github.com/freebsd/freebsd-doc/commit/b992b27125b598a582108cb4550fcd39acbe5334

----

```text
% rg --count sysrc /usr/doc/documentation/content/
/usr/doc/documentation/content/de/books/handbook/security/_index.adoc:4
/usr/doc/documentation/content/de/books/handbook/virtualization/_index.adoc:12
/usr/doc/documentation/content/de/books/handbook/advanced-networking/_index.adoc:1
/usr/doc/documentation/content/de/books/handbook/multimedia/_index.adoc:2
/usr/doc/documentation/content/de/books/handbook/firewalls/_index.adoc:11
/usr/doc/documentation/content/de/books/porters-handbook/pkg-files/_index.adoc:1
/usr/doc/documentation/content/ja/books/handbook/multimedia/_index.adoc:1
/usr/doc/documentation/content/ja/books/handbook/x11/_index.adoc:2
/usr/doc/documentation/content/ru/books/faq/_index.adoc:2
/usr/doc/documentation/content/pt-br/books/handbook/multimedia/_index.adoc:2
/usr/doc/documentation/content/pt-br/books/handbook/security/_index.adoc:3
/usr/doc/documentation/content/pt-br/books/handbook/firewalls/_index.adoc:11
/usr/doc/documentation/content/pt-br/books/handbook/advanced-networking/_index.adoc:1
/usr/doc/documentation/content/pt-br/books/handbook/virtualization/_index.adoc:12
/usr/doc/documentation/content/pt-br/articles/remote-install/_index.po:2
/usr/doc/documentation/content/pt-br/articles/remote-install/_index.adoc:1
/usr/doc/documentation/content/en/books/porters-handbook/pkg-files/_index.adoc:1
/usr/doc/documentation/content/en/books/handbook/multimedia/_index.adoc:4
/usr/doc/documentation/content/en/books/handbook/multimedia/_index.po:4
/usr/doc/documentation/content/en/books/handbook/linuxemu/_index.po:2
/usr/doc/documentation/content/en/books/handbook/linuxemu/_index.adoc:2
/usr/doc/documentation/content/en/books/handbook/firewalls/_index.adoc:11
/usr/doc/documentation/content/en/books/handbook/firewalls/_index.po:11
/usr/doc/documentation/content/en/books/handbook/config/_index.po:1
/usr/doc/documentation/content/en/books/handbook/config/_index.adoc:1
/usr/doc/documentation/content/en/books/handbook/wayland/_index.po:1
/usr/doc/documentation/content/en/books/handbook/wayland/_index.adoc:1
/usr/doc/documentation/content/en/books/handbook/desktop/_index.po:5
/usr/doc/documentation/content/en/books/handbook/desktop/_index.adoc:14
/usr/doc/documentation/content/en/books/handbook/disks/_index.adoc:2
/usr/doc/documentation/content/en/books/handbook/advanced-networking/_index.po:1
/usr/doc/documentation/content/en/books/handbook/disks/_index.po:2
/usr/doc/documentation/content/en/books/handbook/x11/_index.po:5
/usr/doc/documentation/content/en/books/handbook/virtualization/_index.po:4
/usr/doc/documentation/content/en/books/handbook/x11/_index.adoc:5
/usr/doc/documentation/content/en/books/handbook/virtualization/_index.adoc:4
/usr/doc/documentation/content/en/books/handbook/advanced-networking/_index.adoc:1
/usr/doc/documentation/content/en/books/handbook/security/_index.po:4
/usr/doc/documentation/content/en/books/handbook/security/_index.adoc:4
/usr/doc/documentation/content/en/books/faq/_index.adoc:2
/usr/doc/documentation/content/en/books/faq/_index.po:2
/usr/doc/documentation/content/zh-tw/books/handbook/serialcomms/_index.adoc:1
/usr/doc/documentation/content/zh-tw/books/handbook/multimedia/_index.adoc:2
/usr/doc/documentation/content/zh-tw/books/handbook/firewalls/_index.adoc:11
/usr/doc/documentation/content/zh-tw/books/handbook/advanced-networking/_index.adoc:1
/usr/doc/documentation/content/zh-tw/books/handbook/virtualization/_index.adoc:12
/usr/doc/documentation/content/zh-tw/books/handbook/geom/_index.adoc:1
/usr/doc/documentation/content/zh-tw/books/handbook/security/_index.adoc:1
/usr/doc/documentation/content/zh-tw/books/handbook/zfs/_index.adoc:1
/usr/doc/documentation/content/en/articles/remote-install/_index.adoc:1
/usr/doc/documentation/content/en/articles/remote-install/_index.po:1
/usr/doc/documentation/content/es/books/handbook/advanced-networking/_index.po:2
/usr/doc/documentation/content/es/books/handbook/advanced-networking/_index.adoc:1
/usr/doc/documentation/content/es/articles/remote-install/_index.adoc:1
/usr/doc/documentation/content/es/articles/remote-install/_index.po:2
/usr/doc/documentation/content/pl/books/handbook/firewalls/_index.adoc:11
/usr/doc/documentation/content/pl/books/handbook/virtualization/_index.adoc:12
/usr/doc/documentation/content/pl/books/handbook/multimedia/_index.adoc:2
/usr/doc/documentation/content/pl/books/handbook/security/_index.adoc:4
/usr/doc/documentation/content/pl/books/handbook/advanced-networking/_index.adoc:1
% 
```

2023-07-01 18:02 UTC, bsdimp commented
Looks good to me...
But do you really need the "" in this case? they aren't passed through to the sysrc command and module names never have spaces or globbing characters

2023-07-01 19:21 UTC, igalic commented
> Looks good to me... But do you really need the "" in this case? they aren't passed through to the sysrc command and module names never have spaces or globbing characters

good point actually, sysrc correctly quotes by itself

2023-07-01 19:22 UTC, igalic requested changes

2023-07-01 19:22 UTC, igalic commented on share/man/man4/hwpmc.4
> +sysrc kld_list+="hwpmc"
```suggestion
sysrc kld_list+=hwpmc
```

2023-07-02 16:24 UTC, grahamperrin commented
Thank you both. 

<https://github.com/freebsd/freebsd-src/pull/785#issuecomment-1616023557>

> … do you really need the "" in this case? …

Side notes, for a future pull request for the manual page for sysrc(8): 

* content of the [EXAMPLES](https://man.freebsd.org/cgi/man.cgi?query=sysrc&sektion=8&manpath=freebsd-release#EXAMPLES) section is not consistent with direction given (duplicated) in two preceding sections; and formatting of examples within each of those two is inconsistent both within the section, and when compared with the EXAMPLES section
* some examples are misplaced. 

(Now, I realise why I nearly always needed to look at the page two or three times (or look away) to make sense of, and find, the required knowledge.)

2023-07-02 16:32 UTC, grahamperrin commented on share/man/man4/hwpmc.4
> +Alternatively, to compile the driver into the kernel:
Fixes a minor inconsistency. 

Please approve.

2023-07-07 05:28 UTC, bsdimp approved these changes

2023-07-07 05:28 UTC, bsdimp commented on share/man/man4/hwpmc.4
> +Alternatively, to compile the driver into the kernel:
I approved

2023-07-08 06:41 UTC, closed without merging

2023-07-27 05:46 UTC, grahamperrin commented
```
% git -C /usr/src branch
  main
  pkg-stage
  prefer-ee
  releng/13.1
  releng/13.2
  stable/12
* stable/13
% git -C /usr/src cherry-pick -x 666c54d --edit
Auto-merging share/man/man4/hwpmc.4
CONFLICT (content): Merge conflict in share/man/man4/hwpmc.4
error: could not apply 666c54d12ec9... hwpmc(4): instead of manual edition, use sysrc(8)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
% 
```

I dealt with merge conflicts once or twice in the past, but (sorry) recently I just haven't got the head space for anything beyond Git basics. If someone else would like to MFC, please go ahead, thanks. 

https://github.com/freebsd/freebsd-src/commits/stable/13/share/man/man4/hwpmc.4

----

Side note: 

https://github.com/refined-github/refined-github/blob/main/source/features/list-prs-for-file.tsx

- list-prs-for-file

> Alerts you if the current file is altered by an open PR.

2023-07-28 09:43 UTC, grahamperrin commented
First: [thanks to Mina](https://github.com/freebsd/freebsd-src/pull/795#issuecomment-1655244127). 

----

Above, <https://github.com/freebsd/freebsd-src/pull/785#issuecomment-1652949018>

> … Git basics …

Looking at (tcsh) `history` across multiple tabs, it's possible that I omitted a (basic) pull:  

`git -C /usr/src pull --ff-only freebsd stable/13`

<details>
<summary>URLs</summary>

```text
% git -C /usr/src config --list | grep url
remote.origin.url=https://github.com/grahamperrin/freebsd-src.git
remote.upstream.url=https://github.com/freebsd/freebsd-src.git
remote.freebsd.url=https://git.freebsd.org/src.git
remote.freebsd.pushurl=git@repo.freebsd.org:src.git
% 
```

</details>

----

I can't imagine why the `.Dd` date line was treated [as conflict](https://github.com/freebsd/freebsd-src/pull/795#issuecomment-1652983697) in #795, but **not** as a conflict here in #785 …

<details>
<summary>Most recent history</summary>

```text
  …
  2036  8:50    git -C /usr/src reset --hard HEAD
  2037  8:50    git -C /usr/src pull --ff-only freebsd stable/13
  2038  8:51    git -C /usr/src cherry-pick -x 3541d90 --edit
  2039  8:51    nano /usr/src/lib/geom/part/gpart.8
  2040  8:52    git -C /usr/src status
  2041  8:53    git -C /usr/src add lib/geom/part/gpart.8 && git -C /usr/src commit
  2042  8:57    git -C /usr/src show
  2043  8:57    git -C /usr/src push freebsd stable/13
  2044  9:14    git -C /usr/src cherry-pick -x 666c54d --edit
  2045  9:17    git -C /usr/src show
  2046  9:17    git -C /usr/src push freebsd stable/13
```

</details>