bin/ipf: Fix some typos
freebsd/freebsd-src pull request #867
Opened 2023-10-15 16:04 UTC by ElyesH

2023-10-16 19:11 UTC, grahamperrin requested changes

2023-10-16 19:11 UTC, grahamperrin commented on sbin/ipf/ipnat/ipnat.5
> +For TCP and UDP packets, it is possible to both match on the destianation
```suggestion
For TCP and UDP packets, it is possible to both match on the destination
```

2023-10-16 19:11 UTC, grahamperrin commented on sbin/ipf/ipf/ipf.5
>  filtre rule that is a group head but does not match any of the rules
```suggestion
filter rule that is a group head but does not match any of the rules
```

2023-10-16 19:11 UTC, grahamperrin commented on sbin/ipf/ipf/ipf.5
> +the occurence count for that packet. The previously logged packet
```suggestion
the occurrence count for that packet. The previously logged packet
```

2023-10-16 19:11 UTC, grahamperrin commented on sbin/ipf/ipf/ipf.5
>  will turn itself off at.
```suggestion
will turn itself off.
```

Not misspelt, but grammatically wrong (given the 'at' in the preceding line).

2023-10-16 19:11 UTC, grahamperrin commented on sbin/ipf/ipnat/ipnat.5
>  and the use of comma.
```suggestion
and the use of a comma.
```

2023-10-17 17:18 UTC, ElyesH commented
Done
Thx

2023-10-17 20:38 UTC, grahamperrin commented on sbin/ipf/ipnat/ipnat.5
> +For TCP and UDP packets, it is possible to both match on the destianation
Resolved.

2023-10-17 20:39 UTC, grahamperrin commented on sbin/ipf/ipf/ipf.5
>  filtre rule that is a group head but does not match any of the rules
Resolved.

2023-10-17 20:39 UTC, grahamperrin commented on sbin/ipf/ipf/ipf.5
> +the occurence count for that packet. The previously logged packet
Resolved.

2023-10-17 20:40 UTC, grahamperrin commented on sbin/ipf/ipf/ipf.5
>  will turn itself off at.
Resolved.

2023-10-17 20:41 UTC, grahamperrin commented on sbin/ipf/ipnat/ipnat.5
>  and the use of comma.
Resolved.

2023-10-17 20:43 UTC, grahamperrin commented
Thanks. Gentle hint: if you use GitHub with a desktop browser, the option to accept/commit a suggested change (I can't recall the wording) will automatically resolve and hide.

2024-01-12 08:06 UTC, ElyesH commented
ping

2024-01-15 10:38 UTC, gmshake approved these changes
Looks good to me. Thanks very much!

2024-02-03 04:38 UTC, bsdimp commented
Thanks! Landed.

2024-02-03 04:38 UTC, closed without merging