Fix typo (triple S)
freebsd/freebsd-src pull request #955
Opened 2023-12-26 23:58 UTC by jlduran

2023-12-27 00:05 UTC, bsdimp approved these changes
lgtm

2023-12-27 00:50 UTC, igalic requested changes
can you please amend your commit messages with a reference to this pull request

2023-12-27 02:00 UTC, bsdimp commented
> can you please amend your commit messages with a reference to this pull request

My script automatically adds that, so there's no need.

2023-12-27 04:23 UTC, jlduran commented
> > can you please amend your commit messages with a reference to this pull request
> 
> My script automatically adds that, so there's no need.

Sorry about that. Reverted!

2023-12-27 20:32 UTC, jlduran commented on sys/dev/pms/freebsd/driver/common/lxosapi.c
> +  AGTIAPI_PRINTK( "ostiFreeMemory: debug message %p ### \n",
Trailing white space.

2023-12-28 03:28 UTC, bsdimp commented
merged.

2023-12-28 03:28 UTC, closed without merging