mail: do not handle SIGINT in grabh()
freebsd/freebsd-src pull request #993
Opened 2024-01-04 21:58 UTC by lexiwinter

Both collect() and grabh() install their own handler for SIGINT which uses setjmp().  This results in grabh's handler overwriting collect()'s setjmp state if ^C is entered during grabh() and then again while entering the body, resulting in a crash.

Since the usual reason for typing ^C is to abort sending, which collect()'s SIGINT handler already does, just use collect()'s handler and remove grabh()'s entirely.

PR:		276119
Reported by:	Christopher Davidson <christopher.davidson@gmail.com>

2024-01-04 22:40 UTC, lexiwinter commented
after thinking about this for a bit, the original patch didn't make sense to me.  i think this patch (adding `volatile`) is the correct fix here.

2024-01-05 02:03 UTC, igalic requested changes
In the commit message:

"if ^C if" -> “if ^C is"

2024-01-05 02:05 UTC, lexiwinter commented
grammer fixified

2024-01-05 02:41 UTC, markjdb commented
Applied. Thanks!

2024-01-05 02:41 UTC, closed without merging

2024-01-05 11:11 UTC, igalic commented
ref: https://github.com/freebsd/freebsd-src/commit/6c951b37170f1fb2ae8b4827070743e61b6eaed2